apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: myurl-redirector
  description: Lambda function for URL redirection
  links:
    - url: https://github.com/Cloud-native-engineering/myurl_redirector/tree/main/redirector
      title: GitHub Repository
      icon: github
spec:
  type: service
  lifecycle: production
  owner: myurl-dev
  system: myurl
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: myurl-datahandler
  description: Lambda function for handling data
  links:
    - url: https://github.com/Cloud-native-engineering/myurl_redirector/tree/main/datahandler
      title: GitHub Repository
      icon: github
spec:
  type: service
  lifecycle: production
  owner: myurl-dev
  system: myurl